name: FFA
version: "1.0"
main: de.tzimon.ffa.FFA
author: Tzimon
authors:
  - Skylike

commands:
  setspawn:
    usage: /setspawn
    description: Sets the spawn
  setheight:
    usage: /setheight death|game
    description: Sets heights