name: FFA
version: "1.0"
main: de.tzimon.ffa.FFA
author: Tzimon
authors:
  - Skylike

commands:
  build:
    usage: /build [Player]
    description: Toggles the build mode
  setheight:
    usage: /setheight death|game
    description: Sets heights
  setspawn:
    usage: /setspawn
    description: Sets the spawn